import { db } from "@workspace/db";
import { profilesTable, mediaItemsTable, liveFeedsTable } from "@workspace/db/schema";

const badges = {
  topViewer: { id: "top-viewer", name: "Top Viewer", icon: "👑", color: "#f59e0b", description: "Top spender in streams" },
  loyalFan: { id: "loyal-fan", name: "Loyal Fan", icon: "❤️", color: "#ef4444", description: "Consistent supporter" },
  superFan: { id: "super-fan", name: "Super Fan", icon: "⭐", color: "#eab308", description: "Top tier fan" },
  vipPatron: { id: "vip-patron", name: "VIP Patron", icon: "💎", color: "#8b5cf6", description: "VIP level supporter" },
  legendSpender: { id: "legend-spender", name: "Legend Spender", icon: "🔥", color: "#f97316", description: "Legendary spending tier" },
  risingCreator: { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing creator" },
  hotCreator: { id: "hot-creator", name: "Hot Creator", icon: "🔥", color: "#f97316", description: "Trending creator" },
  topCreator: { id: "top-creator", name: "Top Creator", icon: "🏆", color: "#eab308", description: "Top performer" },
  eliteCreator: { id: "elite-creator", name: "Elite Creator", icon: "💎", color: "#8b5cf6", description: "Elite earnings" },
};

const profiles = [
  {
    id: "profile-1",
    username: "luna_rose",
    displayName: "Luna Rose",
    age: 24,
    location: "Miami, FL",
    gender: "Female",
    bodyType: "Athletic",
    ethnicity: "Latina",
    height: "5'5\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=b6e3f4",
    coverUrl: "https://picsum.photos/seed/luna-cover/1200/400",
    tagline: "Your Miami sunshine ☀️ Live every night 9PM EST",
    bio: "Miami native living my best life. I love the beach, dancing, and deep conversations. I'm here to connect authentically with amazing people. Join my streams for the ultimate vibe!",
    viewerCount: 1247,
    tier: "established",
    rating: 4.9,
    totalEarnings: 8750,
    personalityTraits: ["Adventurous", "Playful", "Passionate", "Empathetic", "Creative"],
    lifestyle: "Active & Social",
    interests: ["Beach life", "Dancing", "Travel", "Music", "Fitness", "Photography"],
    hobbies: ["Salsa dancing", "Yoga", "Cooking", "Reading", "Hiking"],
    lookingFor: "Someone who matches my energy and loves to have fun. Must be confident, kind, and genuinely curious about life.",
    relationshipGoals: "Open to everything from casual connections to something deeper. I believe in chemistry first.",
    liveSchedule: "Mon, Wed, Fri — 9PM–11PM EST | Sat — 8PM–Midnight EST",
    sexualOrientation: "Bisexual",
    followersCount: 12847,
    likesCount: 89234,
    joinedDate: "2023-03-15",
    badges: [badges.hotCreator, badges.topCreator, badges.loyalFan],
  },
  {
    id: "profile-2",
    username: "alex_storm",
    displayName: "Alex Storm",
    age: 28,
    location: "New York, NY",
    gender: "Male",
    bodyType: "Muscular",
    ethnicity: "Mixed",
    height: "6'1\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alexstorm&backgroundColor=c0aede",
    coverUrl: "https://picsum.photos/seed/alex-cover/1200/400",
    tagline: "NYC nightlife & deep conversations 🌆",
    bio: "NYC guy who loves good food, great conversation and making genuine connections. I do Q&As, gaming nights, and sometimes just vibe with my audience. Real talks only.",
    viewerCount: 892,
    tier: "rising",
    rating: 4.7,
    totalEarnings: 3200,
    personalityTraits: ["Witty", "Genuine", "Ambitious", "Laid-back", "Loyal"],
    lifestyle: "City life enthusiast",
    interests: ["Food culture", "Gaming", "Basketball", "Jazz", "Movies", "Entrepreneurship"],
    hobbies: ["Cooking", "Gaming", "Photography", "Working out", "Podcast listening"],
    lookingFor: "Someone genuine who can keep up with my humor and doesn't take life too seriously.",
    relationshipGoals: "Looking for a real connection — friendship first, see where it goes.",
    liveSchedule: "Tue, Thu — 10PM–Midnight EST | Sun — 7PM–10PM EST",
    sexualOrientation: "Straight",
    followersCount: 5632,
    likesCount: 34127,
    joinedDate: "2023-08-22",
    badges: [badges.risingCreator, badges.hotCreator],
  },
  {
    id: "profile-3",
    username: "jade_rivera",
    displayName: "Jade Rivera",
    age: 26,
    location: "Los Angeles, CA",
    gender: "Female",
    bodyType: "Slim",
    ethnicity: "Asian",
    height: "5'3\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=jade&backgroundColor=ffd5dc",
    coverUrl: "https://picsum.photos/seed/jade-cover/1200/400",
    tagline: "LA dreamgirl ✨ Art, vibes & authentic connections",
    bio: "Los Angeles born creative soul. Artist, dreamer, lover of all things beautiful. My streams are an escape from the ordinary — expect art sessions, life talks and genuine connection.",
    viewerCount: 0,
    tier: "rising",
    rating: 4.8,
    totalEarnings: 4100,
    personalityTraits: ["Creative", "Introspective", "Warm", "Artistic", "Spiritual"],
    lifestyle: "Bohemian creative",
    interests: ["Digital art", "Meditation", "Vegan cooking", "Crystals", "Poetry", "Fashion"],
    hobbies: ["Painting", "Journaling", "Hiking trails", "Vintage shopping", "Astrology"],
    lookingFor: "A soulful connection with someone who appreciates depth and creativity over surface-level small talk.",
    relationshipGoals: "Seeking meaningful connection. Open to a slow-burn romance with the right energy.",
    liveSchedule: "Wed, Fri — 8PM–10PM PST | Sunday afternoons",
    sexualOrientation: "Pansexual",
    followersCount: 7891,
    likesCount: 56432,
    joinedDate: "2023-05-10",
    badges: [badges.risingCreator, badges.superFan],
  },
  {
    id: "profile-4",
    username: "marcus_vane",
    displayName: "Marcus Vane",
    age: 31,
    location: "Chicago, IL",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "Black",
    height: "6'2\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=d1d4f9",
    coverUrl: "https://picsum.photos/seed/marcus-cover/1200/400",
    tagline: "Chicago smooth 🎷 Late night vibes every night",
    bio: "Chicago-bred, world-traveled. I bring the smooth energy every night — jazz, good conversation, real stories. I'm not here for games, I'm here for real connection.",
    viewerCount: 634,
    tier: "established",
    rating: 4.8,
    totalEarnings: 11200,
    personalityTraits: ["Smooth", "Confident", "Deep", "Humorous", "Protective"],
    lifestyle: "Urban professional",
    interests: ["Jazz music", "Travel", "Fine dining", "Sports", "Business", "History"],
    hobbies: ["Playing saxophone", "Wine tasting", "Reading biographies", "Mentoring", "Golf"],
    lookingFor: "A woman who knows her worth, has her own goals, and is ready for a real grown-up connection.",
    relationshipGoals: "Long-term connection with someone who complements my energy.",
    liveSchedule: "Mon–Thu — 11PM–1AM CST | Weekend specials",
    sexualOrientation: "Straight",
    followersCount: 9234,
    likesCount: 67891,
    joinedDate: "2022-11-30",
    badges: [badges.topCreator, badges.eliteCreator, badges.loyalFan],
  },
  {
    id: "profile-5",
    username: "seraphina_kiss",
    displayName: "Seraphina Kiss",
    age: 23,
    location: "Las Vegas, NV",
    gender: "Female",
    bodyType: "Curvy",
    ethnicity: "European",
    height: "5'7\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=seraphina&backgroundColor=ffdfbf",
    coverUrl: "https://picsum.photos/seed/sera-cover/1200/400",
    tagline: "Vegas royalty 👑 Luxury vibes, real energy",
    bio: "Las Vegas showgirl energy meets real girl heart. I love luxury, laughter, and making people feel special. My gallery and streams are an experience you won't forget.",
    viewerCount: 0,
    tier: "rising",
    rating: 4.9,
    totalEarnings: 6800,
    personalityTraits: ["Glamorous", "Bubbly", "Confident", "Generous", "Flirtatious"],
    lifestyle: "Luxury & nightlife",
    interests: ["Fashion", "Nightlife", "Fine dining", "Dancing", "Makeup artistry", "Travel"],
    hobbies: ["Pole dancing", "Shopping", "Beauty tutorials", "Event hosting", "Photography"],
    lookingFor: "A confident partner who knows what they want and treats me like the queen I am.",
    relationshipGoals: "Open to exploring connections — luxury experiences preferred!",
    liveSchedule: "Fri & Sat — 10PM–2AM PST | Thu — 9PM",
    sexualOrientation: "Bisexual",
    followersCount: 8341,
    likesCount: 72103,
    joinedDate: "2023-07-04",
    badges: [badges.hotCreator, badges.vipPatron],
  },
  {
    id: "profile-6",
    username: "dante_cruz",
    displayName: "Dante Cruz",
    age: 29,
    location: "Miami, FL",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "Latino",
    height: "6'0\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dante&backgroundColor=b6e3f4",
    coverUrl: "https://picsum.photos/seed/dante-cover/1200/400",
    tagline: "Miami nights, real talks 🌊 2000+ watching nightly",
    bio: "Miami born, world-view mindset. I bring the heat every night — real conversations, real laughs, and a real vibe. My audience is my family. Come join the Cruz crew.",
    viewerCount: 2103,
    tier: "elite",
    rating: 4.9,
    totalEarnings: 22500,
    personalityTraits: ["Charismatic", "Intense", "Loyal", "Funny", "Driven"],
    lifestyle: "Hustler & family man",
    interests: ["Fitness", "Business", "Music production", "Beaches", "Cars", "Cooking"],
    hobbies: ["DJing", "Weight training", "Surfing", "Entrepreneurship", "Mentoring"],
    lookingFor: "Someone who can vibe at 100 mph and still want to slow down and be real at night.",
    relationshipGoals: "Open — I believe in letting things flow naturally.",
    liveSchedule: "Daily — 9PM–Midnight EST (Featured stream)",
    sexualOrientation: "Straight",
    followersCount: 18923,
    likesCount: 134567,
    joinedDate: "2022-09-01",
    badges: [badges.eliteCreator, badges.topCreator, badges.topViewer],
  },
  {
    id: "profile-7",
    username: "nova_wilde",
    displayName: "Nova Wilde",
    age: 25,
    location: "Austin, TX",
    gender: "Female",
    bodyType: "Slim",
    ethnicity: "Mixed",
    height: "5'6\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nova&backgroundColor=c0aede",
    coverUrl: "https://picsum.photos/seed/nova-cover/1200/400",
    tagline: "Austin indie soul 🎸 Music, mystery & real connection",
    bio: "Austin-based indie artist and full-time free spirit. I make music, talk philosophy, and occasionally rant about the universe. My streams are a safe space for real humans.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.6,
    totalEarnings: 1800,
    personalityTraits: ["Quirky", "Deep", "Indie", "Authentic", "Compassionate"],
    lifestyle: "Alternative & artistic",
    interests: ["Indie music", "Philosophy", "Thrift shopping", "Astronomy", "Veganism", "Poetry"],
    hobbies: ["Songwriting", "Guitar", "Hiking", "Stargazing", "Reading sci-fi"],
    lookingFor: "Someone who thinks for themselves and isn't afraid of a good existential crisis conversation at 2AM.",
    relationshipGoals: "Slow burn, deep connection. Quality over quantity always.",
    liveSchedule: "Tue & Thu — 8PM CST | Surprise sessions!",
    sexualOrientation: "Queer",
    followersCount: 2341,
    likesCount: 18934,
    joinedDate: "2024-01-20",
    badges: [badges.risingCreator],
  },
  {
    id: "profile-8",
    username: "kai_phoenix",
    displayName: "Kai Phoenix",
    age: 27,
    location: "Seattle, WA",
    gender: "Non-binary",
    bodyType: "Slim",
    ethnicity: "Asian-American",
    height: "5'8\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
    coverUrl: "https://picsum.photos/seed/kai-cover/1200/400",
    tagline: "Seattle rain & real energy 🌧️ Tech meets art",
    bio: "Seattle-based tech creative and multi-disciplinary artist. I blend code, art, and genuine human connection. My streams are intimate, thoughtful, and always real.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.7,
    totalEarnings: 950,
    personalityTraits: ["Thoughtful", "Innovative", "Expressive", "Gentle", "Curious"],
    lifestyle: "Tech-creative hybrid",
    interests: ["Tech art", "Coffee culture", "Minimalism", "AI", "Photography", "Anime"],
    hobbies: ["Digital art", "Coding projects", "Coffee brewing", "Photography walks", "Manga reading"],
    lookingFor: "Someone who appreciates nuance, values authenticity, and is comfortable with who they are.",
    relationshipGoals: "Connection first — labels come later if they need to come at all.",
    liveSchedule: "Mon & Wed — 7PM PST | Weekend specials",
    sexualOrientation: "Non-binary / Pansexual",
    followersCount: 1892,
    likesCount: 12043,
    joinedDate: "2024-03-01",
    badges: [badges.risingCreator],
  },
  {
    id: "profile-9",
    username: "isabella_storm",
    displayName: "Isabella Storm",
    age: 22,
    location: "New York, NY",
    gender: "Female",
    bodyType: "Petite",
    ethnicity: "Italian-American",
    height: "5'2\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella&backgroundColor=d1d4f9",
    coverUrl: "https://picsum.photos/seed/bella-cover/1200/400",
    tagline: "NYC's sweetheart ☕ Coffee, connection & good vibes",
    bio: "22 and thriving in New York. I do morning coffee streams, afternoon Q&As, and evening vibes. I'm everyone's little sister, best friend, and secret crush all in one.",
    viewerCount: 445,
    tier: "rising",
    rating: 4.8,
    totalEarnings: 3900,
    personalityTraits: ["Sweet", "Bubbly", "Relatable", "Funny", "Caring"],
    lifestyle: "Coffee shop hopper",
    interests: ["Coffee", "Books", "Fashion", "Brunch culture", "Pop culture", "Skincare"],
    hobbies: ["Reading romance novels", "Coffee tasting", "OOTD content", "Journaling", "Pilates"],
    lookingFor: "Someone who texts back, appreciates effort, and can make me laugh every day.",
    relationshipGoals: "Romantic at heart — looking for something real and sweet.",
    liveSchedule: "Daily mornings 9AM–11AM EST | Evening 8PM–10PM EST",
    sexualOrientation: "Straight",
    followersCount: 6234,
    likesCount: 48921,
    joinedDate: "2023-09-15",
    badges: [badges.risingCreator, badges.hotCreator, badges.loyalFan],
  },
  {
    id: "profile-10",
    username: "ryker_dean",
    displayName: "Ryker Dean",
    age: 33,
    location: "Dallas, TX",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "White",
    height: "6'3\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ryker&backgroundColor=ffdfbf",
    coverUrl: "https://picsum.photos/seed/ryker-cover/1200/400",
    tagline: "Dallas alpha energy 🤠 Real talk, no games",
    bio: "Texas-bred, world-class mindset. I'm a former athlete turned entrepreneur. I stream for the real ones — honest conversations, no filter. My audience gets the authentic me.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.7,
    totalEarnings: 2100,
    personalityTraits: ["Alpha", "Honest", "Driven", "Traditional", "Protective"],
    lifestyle: "Athletic & entrepreneurial",
    interests: ["Football", "Business", "Country music", "BBQ culture", "Fitness", "Horses"],
    hobbies: ["Coaching youth sports", "Grilling", "Hunting", "Weight training", "Investing"],
    lookingFor: "A strong woman who has her own goals but isn't afraid to let me be the man.",
    relationshipGoals: "Looking for something serious — I'm at that stage in life.",
    liveSchedule: "Wed & Fri — 9PM CST | Sunday evening",
    sexualOrientation: "Straight",
    followersCount: 3421,
    likesCount: 24567,
    joinedDate: "2023-12-10",
    badges: [badges.risingCreator],
  },
];

const mediaItems = profiles.flatMap(profile => [
  {
    id: `${profile.id}-photo-1`,
    profileId: profile.id,
    type: "photo",
    thumbnailUrl: `https://picsum.photos/seed/${profile.id}-p1/400/500`,
    mediaUrl: `https://picsum.photos/seed/${profile.id}-p1-full/800/1000`,
    isLocked: true,
    creditCost: 50,
    title: "Exclusive Photo 1",
  },
  {
    id: `${profile.id}-photo-2`,
    profileId: profile.id,
    type: "photo",
    thumbnailUrl: `https://picsum.photos/seed/${profile.id}-p2/400/500`,
    mediaUrl: `https://picsum.photos/seed/${profile.id}-p2-full/800/1000`,
    isLocked: true,
    creditCost: 50,
    title: "Exclusive Photo 2",
  },
  {
    id: `${profile.id}-photo-3`,
    profileId: profile.id,
    type: "photo",
    thumbnailUrl: `https://picsum.photos/seed/${profile.id}-p3/400/500`,
    mediaUrl: `https://picsum.photos/seed/${profile.id}-p3-full/800/1000`,
    isLocked: true,
    creditCost: 75,
    title: "Special Photo Set",
  },
  {
    id: `${profile.id}-video-1`,
    profileId: profile.id,
    type: "video",
    thumbnailUrl: `https://picsum.photos/seed/${profile.id}-v1/400/300`,
    mediaUrl: null,
    isLocked: true,
    creditCost: 150,
    title: "Private Video 1",
  },
  {
    id: `${profile.id}-video-2`,
    profileId: profile.id,
    type: "video",
    thumbnailUrl: `https://picsum.photos/seed/${profile.id}-v2/400/300`,
    mediaUrl: null,
    isLocked: true,
    creditCost: 200,
    title: "VIP Video Experience",
  },
]);

const liveFeeds = [
  {
    id: "feed-1",
    hostId: "profile-1",
    hostName: "Luna Rose",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=b6e3f4",
    title: "Evening Chat & Chill ☀️ Miami vibes",
    thumbnailUrl: "https://picsum.photos/seed/feed1/640/360",
    viewerCount: 1247,
    category: "dating",
    isVip: false,
    vipCost: 0,
    tags: ["Miami", "Chill", "Chat", "Dating"],
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    isActive: true,
    badges: [badges.hotCreator, badges.topCreator],
  },
  {
    id: "feed-2",
    hostId: "profile-2",
    hostName: "Alex Storm",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alexstorm&backgroundColor=c0aede",
    title: "Q&A + Games Night 🎮 NYC Edition",
    thumbnailUrl: "https://picsum.photos/seed/feed2/640/360",
    viewerCount: 892,
    category: "entertainment",
    isVip: false,
    vipCost: 0,
    tags: ["Gaming", "Q&A", "NYC", "Fun"],
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    isActive: true,
    badges: [badges.risingCreator],
  },
  {
    id: "feed-3",
    hostId: "profile-4",
    hostName: "Marcus Vane",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=d1d4f9",
    title: "Late Night Vibes 🎷 Jazz & Deep Talks",
    thumbnailUrl: "https://picsum.photos/seed/feed3/640/360",
    viewerCount: 634,
    category: "chat",
    isVip: false,
    vipCost: 0,
    tags: ["Jazz", "Late night", "Deep talks", "Chicago"],
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    isActive: true,
    badges: [badges.topCreator],
  },
  {
    id: "feed-4",
    hostId: "profile-6",
    hostName: "Dante Cruz",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dante&backgroundColor=b6e3f4",
    title: "🔥 Miami Nights LIVE — 2000+ watching!",
    thumbnailUrl: "https://picsum.photos/seed/feed4/640/360",
    viewerCount: 2103,
    category: "dating",
    isVip: false,
    vipCost: 0,
    tags: ["Miami", "Hot", "Dating", "Featured"],
    startedAt: new Date(Date.now() - 900000).toISOString(),
    isActive: true,
    badges: [badges.eliteCreator, badges.topViewer],
  },
  {
    id: "feed-5",
    hostId: "profile-9",
    hostName: "Isabella Storm",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella&backgroundColor=d1d4f9",
    title: "☕ Coffee & Connection — Morning Vibes",
    thumbnailUrl: "https://picsum.photos/seed/feed5/640/360",
    viewerCount: 445,
    category: "dating",
    isVip: true,
    vipCost: 500,
    tags: ["Coffee", "Morning", "Connection", "VIP"],
    startedAt: new Date(Date.now() - 5400000).toISOString(),
    isActive: true,
    badges: [badges.risingCreator, badges.hotCreator],
  },
];

async function seed() {
  console.log("Seeding VibeLink database...");
  
  // Clear existing data
  await db.delete(mediaItemsTable);
  await db.delete(liveFeedsTable);
  await db.delete(profilesTable);
  
  // Insert profiles
  for (const profile of profiles) {
    await db.insert(profilesTable).values(profile).onConflictDoUpdate({
      target: profilesTable.id,
      set: profile,
    });
  }
  console.log(`Inserted ${profiles.length} profiles`);
  
  // Insert media items
  for (const item of mediaItems) {
    await db.insert(mediaItemsTable).values(item).onConflictDoUpdate({
      target: mediaItemsTable.id,
      set: item,
    });
  }
  console.log(`Inserted ${mediaItems.length} media items`);
  
  // Insert live feeds
  for (const feed of liveFeeds) {
    await db.insert(liveFeedsTable).values(feed).onConflictDoUpdate({
      target: liveFeedsTable.id,
      set: feed,
    });
  }
  console.log(`Inserted ${liveFeeds.length} live feeds`);
  
  console.log("✅ Seeding complete!");
}

seed().catch(console.error);
