export const MOCK_PROFILES = [
  {
    id: "profile-1",
    username: "luna_rose",
    displayName: "Luna Rose",
    age: 24,
    location: "Miami, FL",
    gender: "Female",
    bodyType: "Athletic",
    ethnicity: "Latina",
    height: "5'5\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=b6e3f4",
    coverUrl: "https://picsum.photos/seed/luna-cover/1200/400",
    tagline: "Your Miami sunshine ☀️ Live every night 9PM EST",
    bio: "Miami native living my best life. I love the beach, dancing, and deep conversations. I'm here to connect authentically with amazing people. Join my streams for the ultimate vibe!",
    viewerCount: 1247,
    tier: "established",
    rating: 4.9,
    totalEarnings: 8750,
    personalityTraits: ["Adventurous", "Playful", "Passionate", "Empathetic"],
    lifestyle: "Active & Social",
    interests: ["Beach life", "Dancing", "Travel", "Music", "Fitness"],
    hobbies: ["Salsa dancing", "Yoga", "Cooking", "Reading"],
    lookingFor: "Someone who matches my energy and loves to have fun.",
    relationshipGoals: "Open to everything from casual connections to something deeper.",
    liveSchedule: "Mon, Wed, Fri — 9PM–11PM EST | Sat — 8PM–Midnight EST",
    sexualPreferences: { orientation: "Bisexual", lockedDetails: "Unlock to view intimate preferences, turn-ons, turn-offs and fantasies" },
    followersCount: 12847,
    likesCount: 89234,
    joinedDate: "2023-03-15",
    badges: [
      { id: "hot-creator", name: "Hot Creator", icon: "🔥", color: "#f97316", description: "Trending creator" },
      { id: "top-creator", name: "Top Creator", icon: "🏆", color: "#eab308", description: "Top performer" },
    ],
    mediaItems: [
      { id: "profile-1-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/luna-p1/400/500", isLocked: true, creditCost: 50, title: "Exclusive Photo 1" },
      { id: "profile-1-photo-2", type: "photo", thumbnailUrl: "https://picsum.photos/seed/luna-p2/400/500", isLocked: true, creditCost: 50, title: "Exclusive Photo 2" },
      { id: "profile-1-photo-3", type: "photo", thumbnailUrl: "https://picsum.photos/seed/luna-p3/400/500", isLocked: true, creditCost: 75, title: "Special Photo Set" },
      { id: "profile-1-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/luna-v1/400/300", isLocked: true, creditCost: 150, title: "Private Video 1" },
      { id: "profile-1-video-2", type: "video", thumbnailUrl: "https://picsum.photos/seed/luna-v2/400/300", isLocked: true, creditCost: 200, title: "VIP Video Experience" },
    ],
  },
  {
    id: "profile-2",
    username: "alex_storm",
    displayName: "Alex Storm",
    age: 28,
    location: "New York, NY",
    gender: "Male",
    bodyType: "Muscular",
    ethnicity: "Mixed",
    height: "6'1\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alexstorm&backgroundColor=c0aede",
    coverUrl: "https://picsum.photos/seed/alex-cover/1200/400",
    tagline: "NYC nightlife & deep conversations 🌆",
    bio: "NYC guy who loves good food, great conversation and making genuine connections. Real talks only.",
    viewerCount: 892,
    tier: "rising",
    rating: 4.7,
    totalEarnings: 3200,
    personalityTraits: ["Witty", "Genuine", "Ambitious", "Laid-back"],
    lifestyle: "City life enthusiast",
    interests: ["Food culture", "Gaming", "Basketball", "Jazz"],
    hobbies: ["Cooking", "Gaming", "Photography", "Working out"],
    lookingFor: "Someone genuine who can keep up with my humor.",
    relationshipGoals: "Looking for a real connection — friendship first.",
    liveSchedule: "Tue, Thu — 10PM–Midnight EST | Sun — 7PM–10PM EST",
    sexualPreferences: { orientation: "Straight", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 5632,
    likesCount: 34127,
    joinedDate: "2023-08-22",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
    ],
    mediaItems: [
      { id: "profile-2-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/alex-p1/400/500", isLocked: true, creditCost: 50, title: "Exclusive Photo 1" },
      { id: "profile-2-photo-2", type: "photo", thumbnailUrl: "https://picsum.photos/seed/alex-p2/400/500", isLocked: true, creditCost: 50, title: "Exclusive Photo 2" },
      { id: "profile-2-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/alex-v1/400/300", isLocked: true, creditCost: 150, title: "Private Video 1" },
    ],
  },
  {
    id: "profile-3",
    username: "jade_rivera",
    displayName: "Jade Rivera",
    age: 26,
    location: "Los Angeles, CA",
    gender: "Female",
    bodyType: "Slim",
    ethnicity: "Asian",
    height: "5'3\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=jade&backgroundColor=ffd5dc",
    coverUrl: "https://picsum.photos/seed/jade-cover/1200/400",
    tagline: "LA dreamgirl ✨ Art, vibes & authentic connections",
    bio: "Los Angeles born creative soul. Artist, dreamer, lover of all things beautiful. My streams are an escape from the ordinary.",
    viewerCount: 0,
    tier: "rising",
    rating: 4.8,
    totalEarnings: 4100,
    personalityTraits: ["Creative", "Introspective", "Warm", "Artistic"],
    lifestyle: "Bohemian creative",
    interests: ["Digital art", "Meditation", "Vegan cooking", "Poetry"],
    hobbies: ["Painting", "Journaling", "Hiking", "Vintage shopping"],
    lookingFor: "A soulful connection with someone who appreciates depth.",
    relationshipGoals: "Seeking meaningful connection. Slow-burn romance.",
    liveSchedule: "Wed, Fri — 8PM–10PM PST | Sunday afternoons",
    sexualPreferences: { orientation: "Pansexual", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 7891,
    likesCount: 56432,
    joinedDate: "2023-05-10",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
    ],
    mediaItems: [
      { id: "profile-3-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/jade-p1/400/500", isLocked: true, creditCost: 50, title: "Art Session Photos" },
      { id: "profile-3-photo-2", type: "photo", thumbnailUrl: "https://picsum.photos/seed/jade-p2/400/500", isLocked: true, creditCost: 75, title: "Special Collection" },
      { id: "profile-3-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/jade-v1/400/300", isLocked: true, creditCost: 150, title: "Studio Session" },
    ],
  },
  {
    id: "profile-4",
    username: "marcus_vane",
    displayName: "Marcus Vane",
    age: 31,
    location: "Chicago, IL",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "Black",
    height: "6'2\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=d1d4f9",
    coverUrl: "https://picsum.photos/seed/marcus-cover/1200/400",
    tagline: "Chicago smooth 🎷 Late night vibes every night",
    bio: "Chicago-bred, world-traveled. I bring the smooth energy every night — jazz, good conversation, real stories.",
    viewerCount: 634,
    tier: "established",
    rating: 4.8,
    totalEarnings: 11200,
    personalityTraits: ["Smooth", "Confident", "Deep", "Humorous"],
    lifestyle: "Urban professional",
    interests: ["Jazz music", "Travel", "Fine dining", "Sports"],
    hobbies: ["Playing saxophone", "Wine tasting", "Reading", "Golf"],
    lookingFor: "A woman who knows her worth and is ready for a real connection.",
    relationshipGoals: "Long-term connection with someone who complements my energy.",
    liveSchedule: "Mon–Thu — 11PM–1AM CST | Weekend specials",
    sexualPreferences: { orientation: "Straight", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 9234,
    likesCount: 67891,
    joinedDate: "2022-11-30",
    badges: [
      { id: "top-creator", name: "Top Creator", icon: "🏆", color: "#eab308", description: "Top performer" },
      { id: "elite-creator", name: "Elite Creator", icon: "💎", color: "#8b5cf6", description: "Elite earnings" },
    ],
    mediaItems: [
      { id: "profile-4-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/marcus-p1/400/500", isLocked: true, creditCost: 50, title: "Exclusive Photo 1" },
      { id: "profile-4-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/marcus-v1/400/300", isLocked: true, creditCost: 150, title: "Late Night Session" },
      { id: "profile-4-video-2", type: "video", thumbnailUrl: "https://picsum.photos/seed/marcus-v2/400/300", isLocked: true, creditCost: 200, title: "VIP Experience" },
    ],
  },
  {
    id: "profile-5",
    username: "seraphina_kiss",
    displayName: "Seraphina Kiss",
    age: 23,
    location: "Las Vegas, NV",
    gender: "Female",
    bodyType: "Curvy",
    ethnicity: "European",
    height: "5'7\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=seraphina&backgroundColor=ffdfbf",
    coverUrl: "https://picsum.photos/seed/sera-cover/1200/400",
    tagline: "Vegas royalty 👑 Luxury vibes, real energy",
    bio: "Las Vegas showgirl energy meets real girl heart. My gallery and streams are an experience you won't forget.",
    viewerCount: 0,
    tier: "rising",
    rating: 4.9,
    totalEarnings: 6800,
    personalityTraits: ["Glamorous", "Bubbly", "Confident", "Generous"],
    lifestyle: "Luxury & nightlife",
    interests: ["Fashion", "Nightlife", "Fine dining", "Dancing"],
    hobbies: ["Pole dancing", "Shopping", "Beauty tutorials", "Photography"],
    lookingFor: "A confident partner who treats me like the queen I am.",
    relationshipGoals: "Open to exploring connections — luxury experiences preferred!",
    liveSchedule: "Fri & Sat — 10PM–2AM PST | Thu — 9PM",
    sexualPreferences: { orientation: "Bisexual", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 8341,
    likesCount: 72103,
    joinedDate: "2023-07-04",
    badges: [
      { id: "hot-creator", name: "Hot Creator", icon: "🔥", color: "#f97316", description: "Trending creator" },
    ],
    mediaItems: [
      { id: "profile-5-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/sera-p1/400/500", isLocked: true, creditCost: 50, title: "Vegas Glam" },
      { id: "profile-5-photo-2", type: "photo", thumbnailUrl: "https://picsum.photos/seed/sera-p2/400/500", isLocked: true, creditCost: 75, title: "Luxury Collection" },
      { id: "profile-5-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/sera-v1/400/300", isLocked: true, creditCost: 200, title: "VIP Vegas Night" },
    ],
  },
  {
    id: "profile-6",
    username: "dante_cruz",
    displayName: "Dante Cruz",
    age: 29,
    location: "Miami, FL",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "Latino",
    height: "6'0\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dante&backgroundColor=b6e3f4",
    coverUrl: "https://picsum.photos/seed/dante-cover/1200/400",
    tagline: "Miami nights, real talks 🌊 2000+ watching nightly",
    bio: "Miami born, world-view mindset. I bring the heat every night — real conversations, real laughs, and a real vibe.",
    viewerCount: 2103,
    tier: "elite",
    rating: 4.9,
    totalEarnings: 22500,
    personalityTraits: ["Charismatic", "Intense", "Loyal", "Funny"],
    lifestyle: "Hustler & family man",
    interests: ["Fitness", "Business", "Music production", "Beaches"],
    hobbies: ["DJing", "Weight training", "Surfing", "Entrepreneurship"],
    lookingFor: "Someone who can vibe at 100 mph and still slow down.",
    relationshipGoals: "Open — I believe in letting things flow naturally.",
    liveSchedule: "Daily — 9PM–Midnight EST",
    sexualPreferences: { orientation: "Straight", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 18923,
    likesCount: 134567,
    joinedDate: "2022-09-01",
    badges: [
      { id: "elite-creator", name: "Elite Creator", icon: "💎", color: "#8b5cf6", description: "Elite earnings" },
      { id: "top-creator", name: "Top Creator", icon: "🏆", color: "#eab308", description: "Top performer" },
    ],
    mediaItems: [
      { id: "profile-6-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/dante-p1/400/500", isLocked: true, creditCost: 75, title: "Miami Exclusive" },
      { id: "profile-6-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/dante-v1/400/300", isLocked: true, creditCost: 200, title: "Elite Access" },
    ],
  },
  {
    id: "profile-7",
    username: "nova_wilde",
    displayName: "Nova Wilde",
    age: 25,
    location: "Austin, TX",
    gender: "Female",
    bodyType: "Slim",
    ethnicity: "Mixed",
    height: "5'6\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nova&backgroundColor=c0aede",
    coverUrl: "https://picsum.photos/seed/nova-cover/1200/400",
    tagline: "Austin indie soul 🎸 Music, mystery & real connection",
    bio: "Austin-based indie artist and full-time free spirit. My streams are a safe space for real humans.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.6,
    totalEarnings: 1800,
    personalityTraits: ["Quirky", "Deep", "Indie", "Authentic"],
    lifestyle: "Alternative & artistic",
    interests: ["Indie music", "Philosophy", "Thrift shopping", "Astronomy"],
    hobbies: ["Songwriting", "Guitar", "Hiking", "Stargazing"],
    lookingFor: "Someone who isn't afraid of a good existential crisis.",
    relationshipGoals: "Slow burn, deep connection. Quality over quantity.",
    liveSchedule: "Tue & Thu — 8PM CST",
    sexualPreferences: { orientation: "Queer", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 2341,
    likesCount: 18934,
    joinedDate: "2024-01-20",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
    ],
    mediaItems: [
      { id: "profile-7-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/nova-p1/400/500", isLocked: true, creditCost: 50, title: "Studio Session" },
      { id: "profile-7-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/nova-v1/400/300", isLocked: true, creditCost: 150, title: "Acoustic Set" },
    ],
  },
  {
    id: "profile-8",
    username: "kai_phoenix",
    displayName: "Kai Phoenix",
    age: 27,
    location: "Seattle, WA",
    gender: "Non-binary",
    bodyType: "Slim",
    ethnicity: "Asian-American",
    height: "5'8\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
    coverUrl: "https://picsum.photos/seed/kai-cover/1200/400",
    tagline: "Seattle rain & real energy 🌧️ Tech meets art",
    bio: "Seattle-based tech creative. I blend code, art, and genuine human connection.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.7,
    totalEarnings: 950,
    personalityTraits: ["Thoughtful", "Innovative", "Expressive", "Curious"],
    lifestyle: "Tech-creative hybrid",
    interests: ["Tech art", "Coffee culture", "AI", "Photography"],
    hobbies: ["Digital art", "Coding", "Coffee brewing", "Photography walks"],
    lookingFor: "Someone who values authenticity and nuance.",
    relationshipGoals: "Connection first — labels come later.",
    liveSchedule: "Mon & Wed — 7PM PST",
    sexualPreferences: { orientation: "Non-binary / Pansexual", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 1892,
    likesCount: 12043,
    joinedDate: "2024-03-01",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
    ],
    mediaItems: [
      { id: "profile-8-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/kai-p1/400/500", isLocked: true, creditCost: 50, title: "Tech Art Series" },
      { id: "profile-8-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/kai-v1/400/300", isLocked: true, creditCost: 150, title: "Creative Process" },
    ],
  },
  {
    id: "profile-9",
    username: "isabella_storm",
    displayName: "Isabella Storm",
    age: 22,
    location: "New York, NY",
    gender: "Female",
    bodyType: "Petite",
    ethnicity: "Italian-American",
    height: "5'2\"",
    isLive: true,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella&backgroundColor=d1d4f9",
    coverUrl: "https://picsum.photos/seed/bella-cover/1200/400",
    tagline: "NYC's sweetheart ☕ Coffee, connection & good vibes",
    bio: "22 and thriving in New York. I'm everyone's little sister, best friend, and secret crush all in one.",
    viewerCount: 445,
    tier: "rising",
    rating: 4.8,
    totalEarnings: 3900,
    personalityTraits: ["Sweet", "Bubbly", "Relatable", "Funny"],
    lifestyle: "Coffee shop hopper",
    interests: ["Coffee", "Books", "Fashion", "Brunch culture"],
    hobbies: ["Reading romance novels", "Coffee tasting", "Journaling", "Pilates"],
    lookingFor: "Someone who texts back and can make me laugh every day.",
    relationshipGoals: "Romantic at heart — looking for something real and sweet.",
    liveSchedule: "Daily mornings 9AM–11AM EST | Evening 8PM–10PM EST",
    sexualPreferences: { orientation: "Straight", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 6234,
    likesCount: 48921,
    joinedDate: "2023-09-15",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
      { id: "hot-creator", name: "Hot Creator", icon: "🔥", color: "#f97316", description: "Trending" },
    ],
    mediaItems: [
      { id: "profile-9-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/bella-p1/400/500", isLocked: true, creditCost: 50, title: "Coffee Date" },
      { id: "profile-9-photo-2", type: "photo", thumbnailUrl: "https://picsum.photos/seed/bella-p2/400/500", isLocked: true, creditCost: 50, title: "NYC Lookbook" },
      { id: "profile-9-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/bella-v1/400/300", isLocked: true, creditCost: 150, title: "Morning Routine" },
    ],
  },
  {
    id: "profile-10",
    username: "ryker_dean",
    displayName: "Ryker Dean",
    age: 33,
    location: "Dallas, TX",
    gender: "Male",
    bodyType: "Athletic",
    ethnicity: "White",
    height: "6'3\"",
    isLive: false,
    isCreator: true,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ryker&backgroundColor=ffdfbf",
    coverUrl: "https://picsum.photos/seed/ryker-cover/1200/400",
    tagline: "Dallas alpha energy 🤠 Real talk, no games",
    bio: "Texas-bred, world-class mindset. Former athlete turned entrepreneur. No filter, always authentic.",
    viewerCount: 0,
    tier: "starter",
    rating: 4.7,
    totalEarnings: 2100,
    personalityTraits: ["Alpha", "Honest", "Driven", "Traditional"],
    lifestyle: "Athletic & entrepreneurial",
    interests: ["Football", "Business", "Country music", "Fitness"],
    hobbies: ["Coaching youth sports", "Grilling", "Hunting", "Investing"],
    lookingFor: "A strong woman who has her own goals.",
    relationshipGoals: "Looking for something serious — I'm at that stage in life.",
    liveSchedule: "Wed & Fri — 9PM CST | Sunday evening",
    sexualPreferences: { orientation: "Straight", lockedDetails: "Unlock to view intimate preferences" },
    followersCount: 3421,
    likesCount: 24567,
    joinedDate: "2023-12-10",
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rapidly growing" },
    ],
    mediaItems: [
      { id: "profile-10-photo-1", type: "photo", thumbnailUrl: "https://picsum.photos/seed/ryker-p1/400/500", isLocked: true, creditCost: 50, title: "Texas Life" },
      { id: "profile-10-video-1", type: "video", thumbnailUrl: "https://picsum.photos/seed/ryker-v1/400/300", isLocked: true, creditCost: 150, title: "Behind the Scenes" },
    ],
  },
];

export const MOCK_LIVE_FEEDS = [
  {
    id: "feed-1",
    hostId: "profile-1",
    hostName: "Luna Rose",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=luna&backgroundColor=b6e3f4",
    title: "Evening Chat & Chill ☀️ Miami vibes",
    thumbnailUrl: "https://picsum.photos/seed/feed1/640/360",
    viewerCount: 1247,
    category: "dating",
    isVip: false,
    vipCost: 0,
    tags: ["Miami", "Chill", "Chat", "Dating"],
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    badges: [
      { id: "hot-creator", name: "Hot Creator", icon: "🔥", color: "#f97316", description: "Trending" },
    ],
  },
  {
    id: "feed-2",
    hostId: "profile-2",
    hostName: "Alex Storm",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alexstorm&backgroundColor=c0aede",
    title: "Q&A + Games Night 🎮 NYC Edition",
    thumbnailUrl: "https://picsum.photos/seed/feed2/640/360",
    viewerCount: 892,
    category: "entertainment",
    isVip: false,
    vipCost: 0,
    tags: ["Gaming", "Q&A", "NYC", "Fun"],
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    badges: [],
  },
  {
    id: "feed-3",
    hostId: "profile-4",
    hostName: "Marcus Vane",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=d1d4f9",
    title: "Late Night Vibes 🎷 Jazz & Deep Talks",
    thumbnailUrl: "https://picsum.photos/seed/feed3/640/360",
    viewerCount: 634,
    category: "chat",
    isVip: false,
    vipCost: 0,
    tags: ["Jazz", "Late night", "Deep talks"],
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    badges: [],
  },
  {
    id: "feed-4",
    hostId: "profile-6",
    hostName: "Dante Cruz",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dante&backgroundColor=b6e3f4",
    title: "🔥 Miami Nights LIVE — 2000+ watching!",
    thumbnailUrl: "https://picsum.photos/seed/feed4/640/360",
    viewerCount: 2103,
    category: "dating",
    isVip: false,
    vipCost: 0,
    tags: ["Miami", "Hot", "Dating", "Featured"],
    startedAt: new Date(Date.now() - 900000).toISOString(),
    badges: [
      { id: "elite-creator", name: "Elite Creator", icon: "💎", color: "#8b5cf6", description: "Elite" },
    ],
  },
  // ── Featured / promoted streams (ids must match FEATURED_STREAMS in LiveFeeds.tsx) ──
  {
    id: "feat-1",
    hostId: "profile-feat-1",
    hostName: "Aria Valencia",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ariavalencia&backgroundColor=b6e3f4",
    title: "VIP Lounge Night 🔥",
    thumbnailUrl: "https://picsum.photos/seed/feat1/640/360",
    viewerCount: 3218,
    category: "dating",
    isVip: false,
    vipCost: 0,
    tags: ["VIP", "Lounge", "Night", "Featured"],
    startedAt: new Date(Date.now() - 2700000).toISOString(),
    badges: [
      { id: "legend", name: "Legend", icon: "⭐", color: "#f59e0b", description: "Legend Boost" },
    ],
  },
  {
    id: "feat-2",
    hostId: "profile-feat-2",
    hostName: "Mia Rose",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=miarose&backgroundColor=fde68a",
    title: "Midnight Chat Session ✨",
    thumbnailUrl: "https://picsum.photos/seed/feat2/640/360",
    viewerCount: 1847,
    category: "chat",
    isVip: false,
    vipCost: 0,
    tags: ["Midnight", "Chat", "Chill", "Featured"],
    startedAt: new Date(Date.now() - 4500000).toISOString(),
    badges: [
      { id: "inferno", name: "Inferno", icon: "🔥", color: "#f97316", description: "Inferno Boost" },
    ],
  },
  {
    id: "feat-3",
    hostId: "profile-feat-3",
    hostName: "Celeste Kim",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=celestekim&backgroundColor=c0aede",
    title: "Exclusive Q&A with Celeste",
    thumbnailUrl: "https://picsum.photos/seed/feat3/640/360",
    viewerCount: 1293,
    category: "entertainment",
    isVip: false,
    vipCost: 0,
    tags: ["Q&A", "Exclusive", "Entertainment", "Featured"],
    startedAt: new Date(Date.now() - 3300000).toISOString(),
    badges: [
      { id: "inferno", name: "Inferno", icon: "🔥", color: "#f97316", description: "Inferno Boost" },
    ],
  },
  {
    id: "feed-5",
    hostId: "profile-9",
    hostName: "Isabella Storm",
    hostAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella&backgroundColor=d1d4f9",
    title: "☕ Coffee & Connection — VIP Morning",
    thumbnailUrl: "https://picsum.photos/seed/feed5/640/360",
    viewerCount: 445,
    category: "dating",
    isVip: true,
    vipCost: 500,
    tags: ["Coffee", "Morning", "Connection", "VIP"],
    startedAt: new Date(Date.now() - 5400000).toISOString(),
    badges: [
      { id: "rising-star", name: "Rising Star", icon: "🌟", color: "#06b6d4", description: "Rising" },
    ],
  },
];

export const MOCK_GIFTS = [
  // Romantic
  { id: "rose", name: "Rose", emoji: "🌹", creditCost: 25, description: "A classic symbol of love", category: "romantic" },
  { id: "kiss", name: "Kiss", emoji: "💋", creditCost: 30, description: "Send a virtual kiss", category: "romantic" },
  { id: "heart-explosion", name: "Heart Explosion", emoji: "💥", creditCost: 75, description: "Burst with love", category: "romantic" },
  { id: "bouquet", name: "Bouquet", emoji: "💐", creditCost: 60, description: "A gorgeous floral arrangement", category: "romantic" },
  { id: "love-letter", name: "Love Letter", emoji: "💌", creditCost: 20, description: "A heartfelt message", category: "romantic" },
  { id: "heart-eyes", name: "Heart Eyes", emoji: "😍", creditCost: 15, description: "Totally smitten", category: "romantic" },
  { id: "teddy-bear", name: "Teddy Bear", emoji: "🧸", creditCost: 45, description: "Warm and cuddly", category: "romantic" },
  { id: "cupid", name: "Cupid's Arrow", emoji: "🏹", creditCost: 55, description: "Struck by love", category: "romantic" },
  // Sweet
  { id: "chocolate", name: "Chocolate Box", emoji: "🍫", creditCost: 50, description: "Sweet and indulgent", category: "sweet" },
  { id: "cake", name: "Birthday Cake", emoji: "🎂", creditCost: 65, description: "Celebrate with cake!", category: "sweet" },
  { id: "candy", name: "Candy Bag", emoji: "🍬", creditCost: 20, description: "Sweet treats for sweet people", category: "sweet" },
  { id: "ice-cream", name: "Ice Cream", emoji: "🍦", creditCost: 30, description: "Cool and sweet", category: "sweet" },
  { id: "macaron", name: "Macarons", emoji: "🫧", creditCost: 40, description: "French delicacy", category: "sweet" },
  { id: "strawberry", name: "Strawberries", emoji: "🍓", creditCost: 35, description: "Fresh and flirty", category: "sweet" },
  // Fun
  { id: "fire", name: "Fire", emoji: "🔥", creditCost: 40, description: "They're on fire!", category: "fun" },
  { id: "confetti", name: "Confetti Pop", emoji: "🎊", creditCost: 30, description: "Time to celebrate!", category: "fun" },
  { id: "rocket", name: "Rocket", emoji: "🚀", creditCost: 80, description: "Blast off!", category: "fun" },
  { id: "disco-ball", name: "Disco Ball", emoji: "🪩", creditCost: 75, description: "Let's dance!", category: "fun" },
  { id: "lightning", name: "Lightning Bolt", emoji: "âš¡", creditCost: 50, description: "Electric energy!", category: "fun" },
  { id: "party-hat", name: "Party Hat", emoji: "🎉", creditCost: 25, description: "Party time!", category: "fun" },
  { id: "magic-wand", name: "Magic Wand", emoji: "🪄", creditCost: 60, description: "You're magical", category: "fun" },
  { id: "gaming", name: "Game Controller", emoji: "🎮", creditCost: 45, description: "Game on!", category: "fun" },
  // Luxury
  { id: "champagne", name: "Champagne", emoji: "🍾", creditCost: 100, description: "Celebrate in style", category: "luxury" },
  { id: "diamond-ring", name: "Diamond Ring", emoji: "💍", creditCost: 200, description: "A sparkling statement", category: "luxury" },
  { id: "luxury-bag", name: "Luxury Bag", emoji: "👜", creditCost: 300, description: "Designer chic", category: "luxury" },
  { id: "watch", name: "Luxury Watch", emoji: "⌚", creditCost: 250, description: "Timeless style", category: "luxury" },
  { id: "perfume", name: "Perfume", emoji: "🧴", creditCost: 120, description: "Scent of elegance", category: "luxury" },
  { id: "jewelry", name: "Jewelry Box", emoji: "💎", creditCost: 350, description: "Dazzling collection", category: "luxury" },
  { id: "red-dress", name: "Red Dress", emoji: "👗", creditCost: 175, description: "Dressed to impress", category: "luxury" },
  { id: "sunglasses", name: "Designer Shades", emoji: "🕶️", creditCost: 90, description: "Cool and classy", category: "luxury" },
  // Prestige
  { id: "crown", name: "Crown", emoji: "👑", creditCost: 150, description: "Treat them like royalty", category: "prestige" },
  { id: "golden-trophy", name: "Golden Trophy", emoji: "🏆", creditCost: 400, description: "You're a winner!", category: "prestige" },
  { id: "vip-pass-24h", name: "24hr VIP Pass", emoji: "🎫", creditCost: 500, description: "24 hours of VIP lounge access", category: "prestige" },
  { id: "medal", name: "Gold Medal", emoji: "🥇", creditCost: 200, description: "First place always", category: "prestige" },
  { id: "shield", name: "Champion Shield", emoji: "🛡️", creditCost: 300, description: "Defender of the realm", category: "prestige" },
  { id: "gem-throne", name: "Gem Throne", emoji: "🔮", creditCost: 750, description: "Sit on the throne of gems", category: "prestige" },
  { id: "star-badge", name: "Star Badge", emoji: "⭐", creditCost: 100, description: "You're a star!", category: "prestige" },
  // Ultimate
  { id: "sports-car", name: "Sports Car", emoji: "🏎️", creditCost: 500, description: "Vroom vroom!", category: "ultimate" },
  { id: "yacht", name: "Yacht", emoji: "🛥️", creditCost: 1000, description: "Life on the water", category: "ultimate" },
  { id: "private-jet", name: "Private Jet", emoji: "✈️", creditCost: 2000, description: "First class everywhere", category: "ultimate" },
  { id: "angel-wings", name: "Angel Wings", emoji: "👼", creditCost: 600, description: "Heavenly vibes", category: "ultimate" },
  { id: "galaxy", name: "Galaxy", emoji: "🌌", creditCost: 800, description: "Out of this world", category: "ultimate" },
  { id: "island", name: "Private Island", emoji: "🏝️", creditCost: 5000, description: "The ultimate getaway", category: "ultimate" },
  { id: "castle", name: "Castle", emoji: "🏰", creditCost: 3000, description: "Rule your kingdom", category: "ultimate" },
  { id: "rocket-ship", name: "Rocket Ship", emoji: "🛸", creditCost: 1500, description: "To infinity and beyond", category: "ultimate" },
  { id: "universe", name: "Universe", emoji: "🌠", creditCost: 10000, description: "Give them the universe", category: "ultimate" },
];

export const CUSTOMER_TIERS = [
  { id: "starter", label: "Link Starter", minSpend: 0, maxSpend: 49, bonusCredits: 0, discount: 0, boosts: 0, color: "#64748b" },
  { id: "explorer", label: "Link Explorer", minSpend: 50, maxSpend: 199, bonusCredits: 12, discount: 0, boosts: 0, color: "#06b6d4" },
  { id: "connector", label: "Link Connector", minSpend: 200, maxSpend: 499, bonusCredits: 18, discount: 12, boosts: 5, color: "#10b981" },
  { id: "pro", label: "Link Pro", minSpend: 500, maxSpend: 999, bonusCredits: 22, discount: 18, boosts: 12, color: "#8b5cf6" },
  { id: "elite", label: "Link Elite", minSpend: 1000, maxSpend: 2499, bonusCredits: 27, discount: 25, boosts: 20, color: "#f59e0b" },
  { id: "legend", label: "Link Legend", minSpend: 2500, maxSpend: 4999, bonusCredits: 32, discount: 32, boosts: 30, color: "#f97316" },
  { id: "vip", label: "Link VIP", minSpend: 5000, maxSpend: 9999, bonusCredits: 40, discount: 40, boosts: 35, color: "#ef4444" },
  { id: "icon", label: "Link Icon", minSpend: 10000, maxSpend: 24999, bonusCredits: 50, discount: 45, boosts: 50, color: "#ec4899" },
  { id: "titan", label: "Link Titan", minSpend: 25000, maxSpend: 49999, bonusCredits: 60, discount: 50, boosts: 75, color: "#a855f7" },
  { id: "mogul", label: "Link Mogul", minSpend: 50000, maxSpend: 99999, bonusCredits: 75, discount: 55, boosts: 100, color: "#6366f1" },
  { id: "founders", label: "Founders Circle", minSpend: 100000, maxSpend: 249999, bonusCredits: 100, discount: 60, boosts: 150, color: "#14B8A6" },
  { id: "dynasty", label: "Link Dynasty", minSpend: 250000, maxSpend: 499999, bonusCredits: 120, discount: 65, boosts: 200, color: "#f43f5e" },
  { id: "sovereign", label: "Link Sovereign", minSpend: 500000, maxSpend: 999999, bonusCredits: 150, discount: 68, boosts: 300, color: "#7c3aed" },
  { id: "phenomenon", label: "Link Phenomenon", minSpend: 1000000, maxSpend: 2499999, bonusCredits: 180, discount: 72, boosts: 500, color: "#db2777" },
  { id: "deity", label: "Link Deity", minSpend: 2500000, maxSpend: 9999999, bonusCredits: 220, discount: 75, boosts: 750, color: "#ea580c" },
  { id: "eternal", label: "Link Eternal", minSpend: 10000000, maxSpend: Infinity, bonusCredits: 300, discount: 80, boosts: 999, color: "#dc2626" },
];

export const CREATOR_SUB_TIERS = [
  {
    id: "free",
    label: "Free Follow",
    emoji: "🆓",
    price: 0,
    color: "#64748b",
    popular: false,
    perks: [
      "Follow creator publicly",
      "See free public posts",
      "Send messages (10 credits each)",
      "View public live streams",
    ],
    contentAccess: "Public posts only",
    badgeLabel: null,
  },
  {
    id: "fan",
    label: "Fan",
    emoji: "❤️",
    price: 4.99,
    color: "#06b6d4",
    popular: false,
    perks: [
      "Exclusive subscriber-only posts",
      "DMs included (no credit cost)",
      "Fan badge on your profile",
      "Early access to new content",
    ],
    contentAccess: "Exclusive posts + DMs",
    badgeLabel: "Fan ❤️",
  },
  {
    id: "super-fan",
    label: "Super Fan",
    emoji: "🔥",
    price: 9.99,
    color: "#f97316",
    popular: true,
    perks: [
      "Everything in Fan",
      "Full photo gallery access",
      "Behind-the-scenes content",
      "Priority DM queue",
      "Super Fan badge on profile",
    ],
    contentAccess: "Full gallery + BTS",
    badgeLabel: "Super Fan 🔥",
  },
  {
    id: "vip",
    label: "VIP",
    emoji: "💎",
    price: 19.99,
    color: "#8b5cf6",
    popular: false,
    perks: [
      "Everything in Super Fan",
      "Monthly personal video message",
      "Custom shoutout per month",
      "VIP badge + profile frame",
      "Invite to VIP-only live events",
    ],
    contentAccess: "All content + monthly video",
    badgeLabel: "VIP 💎",
  },
  {
    id: "inner-circle",
    label: "Inner Circle",
    emoji: "👑",
    price: 49.99,
    color: "#f43f5e",
    popular: false,
    perks: [
      "Everything in VIP",
      "Monthly 1-on-1 video call (15 min)",
      "Custom content requests (1/mo)",
      "Inner Circle crown badge",
      "Direct priority message line",
      "Name in creator's bio thank-you",
    ],
    contentAccess: "All content + 1:1 call",
    badgeLabel: "Inner Circle 👑",
  },
];

export const CREATOR_TIERS = [
  {
    label: "Starter", min: 0, max: 2500, emoji: "🌱", color: "#64748b",
    badge: "Seedling Badge", title: "Seedling Creator",
    perks: ["Starter profile listing", "Basic earnings dashboard", "Community forum access", "LinkMe welcome kit"],
  },
  {
    label: "Rising", min: 2501, max: 5000, emoji: "⭐", color: "#06b6d4",
    badge: "Rising Star Badge", title: "Rising Star",
    perks: ["Rising Star profile highlight", "Boosted search visibility", "Creator newsletter mention", "Weekly earnings report"],
  },
  {
    label: "Established", min: 5001, max: 15000, emoji: "🔥", color: "#10b981",
    badge: "Flame Badge", title: "Established Creator",
    perks: ["Flame badge on profile", "Category top-10 listing", "Dedicated onboarding coach", "Analytics deep-dive access"],
  },
  {
    label: "Elite", min: 15001, max: 25000, emoji: "💫", color: "#8b5cf6",
    badge: "Elite Badge", title: "Elite Creator",
    perks: ["Elite badge + purple aura frame", "Homepage featured slot (weekly)", "Priority live stream scheduling", "Quarterly strategy call"],
  },
  {
    label: "Partner", min: 25001, max: 75000, emoji: "🤝", color: "#f59e0b",
    badge: "Partner Badge", title: "LinkMe Partner",
    perks: ["Official LinkMe Partner badge", "Dedicated account manager", "Co-marketing campaigns", "Partner Discord community"],
  },
  {
    label: "Top Partner", min: 75001, max: 200000, emoji: "🏅", color: "#f97316",
    badge: "Gold Medal Badge", title: "Top Partner",
    perks: ["Gold medal badge + golden frame", "Algorithm priority boost", "Featured in LinkMe newsletters", "Bi-weekly payout option"],
  },
  {
    label: "Icon", min: 200001, max: 500000, emoji: "🎯", color: "#ef4444",
    badge: "Icon Badge", title: "LinkMe Icon",
    perks: ["Icon badge + custom animated frame", "Spotlight on LinkMe homepage", "Invitation to Creator Summits", "Personal PR support"],
  },
  {
    label: "Superstar", min: 500001, max: 1000000, emoji: "🌟", color: "#ec4899",
    badge: "Superstar Badge", title: "Superstar",
    perks: ["Superstar shooting-star badge", "VIP concierge support team", "Co-branded content opportunities", "Daily payout eligibility"],
  },
  {
    label: "Mogul", min: 1000001, max: 2500000, emoji: "💼", color: "#a855f7",
    badge: "Mogul Badge", title: "Mogul",
    perks: ["Mogul badge + platinum frame aura", "Private creator community access", "Custom merch drop facilitation", "Quarterly gifting package"],
  },
  {
    label: "Titan", min: 2500001, max: 5000000, emoji: "âš¡", color: "#6366f1",
    badge: "Titan Badge", title: "Titan",
    perks: ["Titan lightning badge + animated halo", "Platinum analytics suite", "Co-marketing with LinkMe brand", "Dedicated legal & contract support"],
  },
  {
    label: "Visionary", min: 5000001, max: 10000000, emoji: "🔮", color: "#14B8A6",
    badge: "Visionary Crystal Badge", title: "Visionary",
    perks: ["Visionary crystal badge", "Beta feature access (all platforms)", "Monthly strategy call with leadership", "Custom platform integration options"],
  },
  {
    label: "Legend", min: 10000001, max: 25000000, emoji: "👑", color: "#fbbf24",
    badge: "Legend Crown Badge", title: "Legend",
    perks: ["Legend crown badge + gold halo", "LinkMe Hall of Fame listing", "Annual spotlight video produced by VL", "Exclusive Legend creator retreat"],
  },
  {
    label: "Phenomenon", min: 25000001, max: 50000000, emoji: "🌌", color: "#db2777",
    badge: "Phenomenon Galaxy Badge", title: "Phenomenon",
    perks: ["Galaxy badge + nebula animated frame", "LinkMe Gala annual invitation", "Personal brand consultant (on-staff)", "Custom platform theme built for you"],
  },
  {
    label: "Dynasty", min: 50000001, max: 100000000, emoji: "🏛️", color: "#7c3aed",
    badge: "Dynasty Crest Badge", title: "Dynasty",
    perks: ["Dynasty crest badge + constellation aura", "Advisory board invitation", "Named creator on LinkMe marketing", "Luxury gift commission (quarterly)"],
  },
  {
    label: "Sovereign", min: 100000001, max: 250000000, emoji: "💎", color: "#0ea5e9",
    badge: "Sovereign Diamond Badge", title: "Sovereign",
    perks: ["Sovereign diamond badge + royal halo", "Direct line to LinkMe C-suite", "Equity conversation rights", "Permanent legacy wall recognition"],
  },
  {
    label: "Immortal", min: 250000001, max: Infinity, emoji: "♾️", color: "#f43f5e",
    badge: "Immortal Infinity Badge", title: "Immortal — The Ultimate",
    perks: ["Immortal infinity badge + full aura crown", "Permanent Hall of Fame (with statue)", "LinkMe Immortal title on all materials", "Named heir legacy fund access"],
  },
];
